// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hfbwexffhljrumkrvjlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmYndleGZmaGxqcnVta3J2amxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NTc5MTUsImV4cCI6MjA2MzEzMzkxNX0.yia2RLLpuv6LyeXWZ54l0wPwnvNG6ED3wM87tpfNcoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);